[package]
name = "word_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
regex = "1.11.1"
scraper = "0.22.0"
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.138"
