[package]
name = "title_markdown_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
html2md = "0.2.15"
indicatif = "0.17.11"
rayon = "1.10.0"
regex = "1.11.1"
scraper = "0.22.0"
serde = "1.0.217"
serde_json = "1.0.138"
xmltree = "0.11.0"
